2019-04-10 09:30:47,177 - root - WARNING - connected to Sqlserver.
2019-04-10 09:30:50,213 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:50,214 - root - INFO - Connections to database severed
2019-04-10 09:30:50,918 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:50,918 - root - INFO - database dropped
2019-04-10 09:30:51,108 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:51,108 - root - INFO - New Intermediate databas created
2019-04-10 09:30:51,126 - root - WARNING - connected to Sqlserver.
2019-04-10 09:30:51,126 - root - INFO - Processing: agentes.DBF
2019-04-10 09:30:51,128 - root - INFO - new table to create: "create table HN1.dbo.vw_origin_agentes (rowNum numeric (20), "AGENTE" varchar(max), "NOMBRE" varchar(max), "DIRECCION" varchar(max), "CONTACTO" varchar(max), "CALIDAD" varchar(max), DELETED varchar (5))"
2019-04-10 09:30:51,130 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:51,130 - root - WARNING - Going to insert to table: agentes
2019-04-10 09:30:51,283 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:51,433 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:51,584 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:51,730 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:51,878 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,031 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,178 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,332 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,477 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,626 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,771 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:52,792 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:52,849 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:52,850 - root - WARNING - insert finished
2019-04-10 09:30:52,853 - root - WARNING - connected to Sqlserver.
2019-04-10 09:30:52,853 - root - INFO - Processing: ccvs.DBF
2019-04-10 09:30:52,854 - root - INFO - new table to create: "create table HN1.dbo.vw_origin_ccvs (rowNum numeric (20), "CCV" varchar(max), "NRO_SOLICI" varchar(max), DELETED varchar (5))"
2019-04-10 09:30:52,855 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:52,856 - root - WARNING - Going to insert to table: ccvs
2019-04-10 09:30:52,933 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,011 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,091 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,172 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,250 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,330 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,406 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,482 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,561 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,639 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,716 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,795 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,876 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:53,952 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,030 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,109 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,186 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,265 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,342 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,418 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,498 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,575 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,651 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,730 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,807 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,884 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:54,962 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,038 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,114 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,192 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,269 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,345 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,420 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,498 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,577 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,656 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,880 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:55,956 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,034 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,113 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,191 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,272 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,351 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,429 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,506 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,587 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,664 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,742 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,822 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,898 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:56,976 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,055 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,131 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,212 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,296 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,376 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,453 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,531 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,610 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,689 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,770 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,849 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,930 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:30:57,972 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,041 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,042 - root - WARNING - insert finished
2019-04-10 09:30:58,042 - root - WARNING - connected to Sqlserver.
2019-04-10 09:30:58,042 - root - INFO - Processing: codigos.dbf
2019-04-10 09:30:58,043 - root - INFO - new table to create: "create table HN1.dbo.vw_origin_codigos (rowNum numeric (20), "ID_CODIGO" varchar(max), "CODIGO" varchar(max), "DESCRIPCOD" varchar(max), DELETED varchar (5))"
2019-04-10 09:30:58,046 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,046 - root - WARNING - Going to insert to table: codigos
2019-04-10 09:30:58,051 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,052 - root - WARNING - insert finished
2019-04-10 09:30:58,052 - root - WARNING - connected to Sqlserver.
2019-04-10 09:30:58,052 - root - INFO - Processing: eventab.dbf
2019-04-10 09:30:58,053 - root - INFO - new table to create: "create table HN1.dbo.vw_origin_eventab (rowNum numeric (20), "EVENTO" varchar(max), "DESCRIP" varchar(max), "TIPO_EVENT" varchar(max), "INFO_ADI" varchar(max), "ETI_COMENT" varchar(max), "ETI_NUMERO" varchar(max), DELETED varchar (5))"
2019-04-10 09:30:58,055 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,055 - root - WARNING - Going to insert to table: eventab
2019-04-10 09:30:58,081 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,085 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,085 - root - WARNING - insert finished
2019-04-10 09:30:58,085 - root - WARNING - connected to Sqlserver.
2019-04-10 09:30:58,085 - root - INFO - Processing: marca.DBF
2019-04-10 09:30:58,087 - root - INFO - new table to create: "create table HN1.dbo.vw_origin_marca (rowNum numeric (20), "NRO_SOLICI" varchar(max), "SOLICITADA" varchar(max), "TIPO_MARCA" varchar(max), "SIGNO" varchar(max), "NOM_MARCA" varchar(max), "REGISTRO" varchar(max), "REGISTRADA" varchar(max), "RENUEVA" varchar(max), "EXPIRA" varchar(max), "AGENTE" varchar(max), "STATUS" varchar(max), "STAT_DESDE" varchar(max), "PESO_RASGO" varchar(max), "LARFON" varchar(max), "PESO_R" varchar(max), "PUBLICADA" varchar(max), "DIARIO" varchar(max), "LIMITACION" varchar(max), "HORA" varchar(max), "RTOMO" varchar(max), "RFOLIO" varchar(max), "RESERVA" varchar(max), "NRO_PODER" varchar(max), "MODIFICA" varchar(max), "NRO_GACETA" varchar(max), "QUIEN" varchar(max), "CALIDAD" varchar(max), "CLASE" varchar(max), "MODIFICADO" varchar(max), "ANUALIDAD" varchar(max), "NRO_RESOL" varchar(max), "LEY" varchar(max), "CLASES_TXT" varchar(max), DELETED varchar (5))"
2019-04-10 09:30:58,089 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105094E0>
2019-04-10 09:30:58,089 - root - WARNING - Going to insert to table: marca
2019-04-10 09:30:59,259 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105095D0>
2019-04-10 09:31:00,439 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB10509558>
2019-04-10 09:31:01,665 - root - ERROR - >>>>>>>>>>>>>>> issue with insert query <pyodbc.Cursor object at 0x000001BB105095D0>
